title = 'Majority Voting'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/885"

[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "small.cpp"
    number = 5

[[tests]]
    name = "max_random.cpp"
    number = 5

[[solutions]]
    name = "naive.cpp"
    allow_tle = true

[params]
    N_MIN = 1
    N_MAX = 500_000
    Q_MIN = 1
    Q_MAX = 500_000
    A_MIN = 0
    A_MAX = 1_000_000_000
