title = 'Deque'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/1342"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "small.cpp"
    number = 10
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max_random.cpp"
    number = 20

[params]
    MIN_Q = 1
    MAX_Q = 500_000
    MIN_X = 0
    MAX_X = 1_000_000_000
