title = 'Static Range Sum with Upper Bound'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/1332"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "small_a_x.cpp"
    number = 3

[[solutions]]
    name = "naive.cpp"
    allow_tle = true

[params]
    MAX_N_Q = 500_000
    MAX_A_X = 1_000_000_000